version: "3.5"
services:
  # Orion-LD context broker
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: community2-fiware-orion
    depends_on:
      - mongo-db
    expose:
      - "2376"  # Changed to avoid conflict
    ports:
      - "1032:1026"  
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  # MongoDB database
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: community2-mongo-db
    expose:
      - "28031"  # Changed to avoid conflict
    ports:
      - "28031:27017"  
    command: --nojournal
    volumes:
      - mongo-db:/data

volumes:
  mongo-db: ~
