version: "3.5"

services:
  mqtt_mqtt:
    image: toke/mosquitto
    network_mode: bridge
    container_name: mqtt_mqtt
    expose:
      - 1888
    ports:
      - 1888:1883
    restart: unless-stopped
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_config:/mosquitto/config
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mqtt_data:
  mqtt_config:

